# debug cheats
[cheats]
enable = false
unlockAllCrops = false
skipToRound = 1 # skip to nth round

# Config for toolbar here:
[toolbar]
wateringCanAmount = 70
fertilizerAmount = 20

# Config for crops here
[crops]
[crops.corn]
growthTime = 25
value = 10
weight = 10
waterUsage = 7
fertilizerUsage = 40

[crops.soybean]
growthTime = 30
value = 8
weight = 8
waterUsage = 3
fertilizerUsage = -30

[crops.potato]
growthTime = 35
value = 15
weight = 15
waterUsage = 5
fertilizerUsage = 30

[crops.wheat]
growthTime = 50
value = 25
weight = 25
waterUsage = 6
fertilizerUsage = 35

[crops.tomato]
growthTime = 10
value = 5
weight = 3
waterUsage = 7
fertilizerUsage = 50

[round]
roundInfinite = 7 # infinite mode after 7 rounds
cleanCropsAfterRound = true # remove all crops after each round

# Round configurations updated to include cropGoals
[round.1]
gridSizeX = 2
gridSizeY = 2
cropsUnlocked = ["corn"]
time = -1
monocroppingDisabled = true
fertilizerNum = 4

[round.1.cropGoals]
total = 30
minFertilizerLvl = -1
corn = 5

[round.2]
gridSizeX = 3
gridSizeY = 3
cropsUnlocked = ["corn", "soybean"]
time = -1
fertilizerNum = 9

[round.2.cropGoals]
total = 80
minFertilizerLvl = 80
corn = 30
soybean = 20

[round.3]
gridSizeX = 4
gridSizeY = 4
cropsUnlocked = ["corn", "soybean"]
time = -1
fertilizerNum = 16

[round.3.cropGoals]
total = 160
minFertilizerLvl = 50
corn = 60
soybean = 40

[round.4]
gridSizeX = 4
gridSizeY = 4
cropsUnlocked = ["corn", "soybean", "potato"]
time = -1
fertilizerNum = 16

[round.4.cropGoals]
total = 400
minFertilizerLvl = 50
corn = 100
soybean = 80
potato = 120

[round.5]
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato", "tomato"]
time = -1
fertilizerNum = 16

[round.5.cropGoals]
total = 600
minFertilizerLvl = 50
corn = 150
soybean = 100
potato = 200

[round.6]
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato", "tomato", "wheat"]
time = -1
fertilizerNum = 25

[round.6.cropGoals]
total = 800
minFertilizerLvl = 50
corn = 200
soybean = 150
potato = 250
wheat = 200

[round.7]
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato", "wheat", "tomato"]
time = -1
fertilizerNum = 25

[round.7.cropGoals]
total = 1000
minFertilizerLvl = 50
corn = 250
soybean = 200
potato = 300
wheat = 250

[round.infinite]
gridSizeX = 5
gridSizeY = 5
time = 120
cropsUnlocked = ["corn", "soybean", "potato", "wheat", "tomato"]
goalMultiplier = 1.5
fertilizerNum = 25

[round.infinite.cropGoals]
total = 600
minFertilizerLvl = 30
