# debug cheats
[cheats]
enable = false
unlockAllCrops = false
skipToRound = 1 # skip to nth round

# Config for toolbar here:
[toolbar]
wateringCanAmount = 70
fertilizerAmount = 20

# Config for crops here
[crops]
[crops.corn]
growthTime = 25
value = 10
weight = 10
waterUsage = 7
fertilizerUsage = 40

[crops.soybean]
growthTime = 30
value = 8
weight = 8
waterUsage = 3
fertilizerUsage = -30

[crops.potato]
growthTime = 35
value = 15
weight = 15
waterUsage = 5
fertilizerUsage = 30

[crops.wheat]
growthTime = 50
value = 25
weight = 25
waterUsage = 6
fertilizerUsage = 35

[round]
roundInfinite = 7 # infinite after 7 rounds

# Configuration for the rounds
[round.1]
goal = 60
gridSizeX = 2
gridSizeY = 2
cropsUnlocked = ["corn"]
time = 120

[round.2]
goal = 150
gridSizeX = 3
gridSizeY = 3
cropsUnlocked = ["corn", "soybean"]
time = 120

[round.3]
goal = 300
gridSizeX = 4
gridSizeY = 4
cropsUnlocked = ["corn", "soybean"]
time = 180

[round.4]
goal = 800
gridSizeX = 4
gridSizeY = 4
cropsUnlocked = ["corn", "soybean", "potato"]
time = 180

[round.5]
goal = 1200
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato"]
time = 180

[round.6]
goal = 1600
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato", "wheat"]
time = 300

[round.7]
goal = 2000
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato", "wheat"]
time = 360

[round.infinite]
goal = 600  # Goal for round 7
goalMultiplier = 1.5 # Increase the goal by 50% each round
gridSizeX = 5
gridSizeY = 5
time = 120
cropsUnlocked = ["corn", "soybean", "potato", "wheat"]
