# debug cheats
[cheats]
enable = false
unlockAllCrops = false
skipToRound = 1 # skip to nth round

# Config for toolbar here:
[toolbar]
wateringCanAmount = 70
fertilizerAmount = 20

# Config for crops here
[crops]
[crops.corn]
growthTime = 25
value = 10
weight = 10
waterUsage = 7
fertilizerUsage = 40
emoji = '🌽'

[crops.soybean]
growthTime = 30
value = 8
weight = 8
waterUsage = 3
fertilizerUsage = -30
emoji = '🫛'

[crops.potato]
growthTime = 35
value = 15
weight = 15
waterUsage = 5
fertilizerUsage = 30
emoji = '🥔'

[crops.wheat]
growthTime = 50
value = 25
weight = 25
waterUsage = 6
fertilizerUsage = 35
emoji = '🌾'

[crops.tomato]
growthTime = 10
value = 5
weight = 3
waterUsage = 7
fertilizerUsage = 50
emoji = '🍅'

[round]
roundInfinite = 7 # infinite mode after 7 rounds
cleanCropsAfterRound = true # remove all crops after each round

# Round configurations updated to include cropGoals
[round.1]
gridSizeX = 2
gridSizeY = 2
cropsUnlocked = ["corn"]
time = -1
monocroppingDisabled = true
fertilizerNum = 4

[round.1.cropGoals]
total = 0
minFertilizerLvl = -1
corn = 5

[round.2]
gridSizeX = 3
gridSizeY = 3
cropsUnlocked = ["corn", "soybean"]
time = -1
monocroppingDisabled = true
fertilizerNum = 9

[round.2.cropGoals]
total = 0
minFertilizerLvl = 60
corn = 0
soybean = 4

[round.3]
gridSizeX = 3
gridSizeY = 3
cropsUnlocked = ["corn", "soybean", "potato"]
time = -1
fertilizerNum = 16

[round.3.cropGoals]
total = 200
minFertilizerLvl = 50
potato = 10

[round.4]
gridSizeX = 4
gridSizeY = 4
cropsUnlocked = ["corn", "soybean", "potato"]
time = -1
fertilizerNum = 16

[round.4.cropGoals]
total = 100
minFertilizerLvl = 50
corn = 5
soybean = 10

[round.5]
gridSizeX = 4
gridSizeY = 4
cropsUnlocked = ["corn", "soybean", "potato", "wheat"]
time = -1
fertilizerNum = 16

[round.5.cropGoals]
total = 500
minFertilizerLvl = 50
soybean = 9
wheat = 9

[round.6]
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato", "tomato", "wheat"]
time = -1
fertilizerNum = 25

[round.6.cropGoals]
total = 500
minFertilizerLvl = 50
tomato = 30

[round.7]
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato", "wheat", "tomato"]
time = -1
fertilizerNum = 25

[round.7.cropGoals]
total = 600
minFertilizerLvl = 50

[round.infinite]
gridSizeX = 5
gridSizeY = 5
time = 120
cropsUnlocked = ["corn", "soybean", "potato", "wheat", "tomato"]
goalMultiplier = 1.5
fertilizerNum = 25

[round.infinite.cropGoals]
total = 600
minFertilizerLvl = 30
