# Config for crops here
[crops]
[crops.corn]
growthTime = 20
value = 50
weight = 10
waterUsage = 5
fertilizerUsage = 50

[crops.soybean]
growthTime = 40
value = 100
weight = 4
waterUsage = 3
fertilizerUsage = -40

[crops.potato]
growthTime = 46
value = 100
weight = 20
waterUsage = 3
fertilizerUsage = 10

[crops.wheat]
growthTime = 34
value = 100
weight = 15
waterUsage = 8
fertilizerUsage = 20
