# debug cheats
[cheats]
enable = false
unlockAllCrops = false
skipToRound = 1	# skip to nth round

# Config for toolbar here:
[toolbar]
wateringCanAmount = 30
fertilizerAmount = 3

# Config for crops here
[crops]
[crops.corn]
growthTime = 20
value = 50
weight = 10
waterUsage = 5
fertilizerUsage = 50

[crops.soybean]
growthTime = 40
value = 100
weight = 4
waterUsage = 3
fertilizerUsage = -40

[crops.potato]
growthTime = 46
value = 100
weight = 20
waterUsage = 3
fertilizerUsage = 10

[crops.wheat]
growthTime = 34
value = 100
weight = 15
waterUsage = 8
fertilizerUsage = 20

[round]
roundInfinite = 7	# infinite after 7 rounds

# Configuration for the rounds
[round.1]
goal = 50
gridSizeX = 2
gridSizeY = 2
cropsUnlocked = ["corn"]
time = 60

[round.2]
goal = 600
gridSizeX = 3
gridSizeY = 3
cropsUnlocked = ["corn", "soybean"]
time = 120

[round.3]
goal = 700
gridSizeX = 4
gridSizeY = 4
cropsUnlocked = ["corn", "soybean"]
time = 120

[round.4]
goal = 800
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato"]
time = 120

[round.5]
goal = 900
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato"]
time = 120

[round.6]
goal = 1000
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato", "wheat"]
time = 120

[round.7]
goal = 1100
gridSizeX = 5
gridSizeY = 5
cropsUnlocked = ["corn", "soybean", "potato", "wheat"]
time = 120

[round.infinite]
goal = 1400		# Goal for round 7
goalMultiplier = 1.5	# Increase the goal by 50% each round
gridSizeX = 6
gridSizeY = 6
time = 120
cropsUnlocked = ["corn", "soybean", "potato", "wheat"]
